/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade;

/**
 *
 * @author raube
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("/");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("+");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("_");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("*");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addContainerGap(259, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                             
        try {
            if (jTextField2.getText().isBlank() || jTextField3.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de calcular!");
                return;
            }
            
            double n1, n2;
            try {
                n1 = Double.parseDouble(jTextField2.getText().replace(",", "."));
                n2 = Double.parseDouble(jTextField3.getText().replace(",", "."));
            } catch (NumberFormatException e) {
                // Abre a sua tela de erro de letras/caracteres
                erro telaErro = new erro();
                telaErro.setLocationRelativeTo(null);
                telaErro.setVisible(true);
                return;
            }
            
            // AQUI É ONDE CHAMA A SUA NOVA TELA DE ERRO POR ZERO
            if (n2 == 0) {
                erro_dividir telaErroDiv = new erro_dividir();
                telaErroDiv.setLocationRelativeTo(null); // Centraliza a tela
                telaErroDiv.setVisible(true);            // Abre a tela
                return; // Para o código para não fazer a divisão
            }
            
            double r = n1 / n2;
            jLabel1.setText("Resultado: " + r);
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            // Se o campo estiver vazio, solta o aviso padrão
            if (jTextField2.getText().isBlank() || jTextField3.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de calcular!");
                return;
            }
            
            double n1, n2;
            try {
                n1 = Double.parseDouble(jTextField2.getText().replace(",", "."));
                n2 = Double.parseDouble(jTextField3.getText().replace(",", "."));
            } catch (NumberFormatException e) {
                // Se pegou letra/caractere inválido, abre a SUA tela personalizada 'erro'
                erro telaErro = new erro();
                telaErro.setLocationRelativeTo(null); // Centraliza no meio da tela
                telaErro.setVisible(true); // Abre a janela
                return; // Para a execução aqui
            }
            
            double r = n1 + n2;
            jLabel1.setText("Resultado: " + r);
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                        
        try {
            if (jTextField2.getText().isBlank() || jTextField3.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de calcular!");
                return;
            }
            
            double n1, n2;
            try {
                n1 = Double.parseDouble(jTextField2.getText().replace(",", "."));
                n2 = Double.parseDouble(jTextField3.getText().replace(",", "."));
            } catch (NumberFormatException e) {
                erro telaErro = new erro();
                telaErro.setLocationRelativeTo(null);
                telaErro.setVisible(true);
                return;
            }
            
            double r = n1 - n2;
            jLabel1.setText("Resultado: " + r);
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                        
        try {
            if (jTextField2.getText().isBlank() || jTextField3.getText().isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de calcular!");
                return;
            }
            
            double n1, n2;
            try {
                n1 = Double.parseDouble(jTextField2.getText().replace(",", "."));
                n2 = Double.parseDouble(jTextField3.getText().replace(",", "."));
            } catch (NumberFormatException e) {
                erro telaErro = new erro();
                telaErro.setLocationRelativeTo(null);
                telaErro.setVisible(true);
                return;
            }
            
            double r = n1 * n2;
            jLabel1.setText("Resultado: " + r);
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
